# Stubs for websocket._handshake (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._exceptions import *
from ._http import *
from ._logging import *
from ._socket import *
from typing import Any

class handshake_response:
    status: Any = ...
    headers: Any = ...
    subprotocol: Any = ...
    def __init__(self, status, headers, subprotocol) -> None: ...

def handshake(sock, hostname, port, resource, **options): ...
