# Stubs for websocket._ssl_compat (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import ssl as ssl
from ssl import SSLError as SSLError  # type: ignore

HAVE_CONTEXT_CHECK_HOSTNAME: bool
HAVE_SSL: bool

class SSLError(Exception): ...  # type: ignore
