# Stubs for websocket._url (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def parse_url(url): ...
def get_proxy_info(hostname, is_secure, proxy_host: Optional[Any] = ..., proxy_port: int = ..., proxy_auth: Optional[Any] = ..., no_proxy: Optional[Any] = ...): ...
